version: '3'
services:
  iris:
    image: intersystems/iris:2019.1.0S.111.0
    container_name: try-iris
    ports: 
      - "52773:52773"
      - "51773:51773"
    volumes:
     - .:/ISC
    environment:
     - ISC_DATA_DIRECTORY=/ISC/dur
networks:
  default:
    ipam:
      config:
        - subnet: 172.177.0.0/16