#!/bin/bash
#shell wrapper for iris deployed with a docker-compose

not_implemented(){
    printf "\nNot implemented\n"
    exit
}

change_password(){
    ./change_password.sh
    exit
}

load_experience(){
    ./load.sh $1 $2
    exit
}

status(){
    ./status.sh
    exit
}

help_message(){
    ./help.sh
    exit
}

info(){
    ./info.sh
    exit
}


main(){
    export IRIS_WRAPPER_DIR=/opt/ISC
    export VER=1.0
    export myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
    
    # change to the wrapper directory--
    cd $IRIS_WRAPPER_DIR
  

    # Option switch___________________________________
    # valid options are: start, stop, session and reset
    #
    if [ -z "$1" ]
    then
        help_message
        exit
    elif [ "$1" = "password" ]
    then
        change_password
        exit
    elif [ "$1" = "load" ]
    then
        load_experience $2 $3
        exit
    elif [ "$1" = "status" ]
    then
        status
        exit
    elif [ "$1" = "help" ]
    then
        help_message
        exit
    elif [ "$1" = "info" ]
    then
        info
        exit
    else
        help_message
        exit
    fi


}

main $1 $2 $3