#!/bin/bash
#move the compose file to /opt/tempest
#this can be whatever application you want
main(){
    sudo mkdir /opt/tempest
    sudo mv /var/lib/cloud/scripts/per-boot/tempest/run/compose/* /opt/tempest/
    sudo chmod 775 /opt/tempest
    sudo chmod 775 /opt/tempest/*

    #symlink to the executable
    sudo ln -s /opt/tempest/iris /bin/iris
}

main