#!/bin/bash
#Run the compose and load the code here. Both have their own directories.
main(){
    #replace the kitname in the docker-compose file
    sudo chmod 775 /var/lib/cloud/scripts/per-boot/tempest/build/config.sh
    sudo docker-compose -f /opt/ISC/docker-compose.yml up --build --detach
}
main
